//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Suma", ReplyAction="*")]
        double Suma(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Suma", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SumaAsync(int a, int b);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DateNowResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DateNow", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.DateNowResponse DateNow(WindowsFormsApp1.ServiceReference1.DateNowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DateNow", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.DateNowResponse> DateNowAsync(WindowsFormsApp1.ServiceReference1.DateNowRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DateNowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DateNow", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.DateNowRequestBody Body;
        
        public DateNowRequest() {
        }
        
        public DateNowRequest(WindowsFormsApp1.ServiceReference1.DateNowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DateNowRequestBody {
        
        public DateNowRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DateNowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DateNowResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.DateNowResponseBody Body;
        
        public DateNowResponse() {
        }
        
        public DateNowResponse(WindowsFormsApp1.ServiceReference1.DateNowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DateNowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DateNowResult;
        
        public DateNowResponseBody() {
        }
        
        public DateNowResponseBody(string DateNowResult) {
            this.DateNowResult = DateNowResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApp1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.WebService1Soap>, WindowsFormsApp1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Suma(int a, int b) {
            return base.Channel.Suma(a, b);
        }
        
        public System.Threading.Tasks.Task<double> SumaAsync(int a, int b) {
            return base.Channel.SumaAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.DateNowResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.DateNow(WindowsFormsApp1.ServiceReference1.DateNowRequest request) {
            return base.Channel.DateNow(request);
        }
        
        public string DateNow() {
            WindowsFormsApp1.ServiceReference1.DateNowRequest inValue = new WindowsFormsApp1.ServiceReference1.DateNowRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.DateNowRequestBody();
            WindowsFormsApp1.ServiceReference1.DateNowResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).DateNow(inValue);
            return retVal.Body.DateNowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.DateNowResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.DateNowAsync(WindowsFormsApp1.ServiceReference1.DateNowRequest request) {
            return base.Channel.DateNowAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.DateNowResponse> DateNowAsync() {
            WindowsFormsApp1.ServiceReference1.DateNowRequest inValue = new WindowsFormsApp1.ServiceReference1.DateNowRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.DateNowRequestBody();
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).DateNowAsync(inValue);
        }
    }
}
